apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jd62asnol-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:59cf9a00be8b978da13894b80fce0680749682e9@sha256:2cb465cec33742bbd46eafb7dccd73d1421e7b54a69bb1800204343104d472b3
          name: container-image
